steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'API_KEY=${_API_KEY}',
      '-t', 'gcr.io/$PROJECT_ID/spot-advisor',
      '.'
    ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/spot-advisor']
images:
  - 'gcr.io/$PROJECT_ID/spot-advisor'
substitutions:
  _API_KEY: '' # Default empty, must be provided at trigger time
